plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.flywaydb.flyway' version '10.17.1'
}

group = 'com.vmware'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

ext {
    set('javaCfenvVersion', "4.0.1")
    set('springCloudServicesVersion', "4.4.0")
    set('springCloudVersion', "2025.1.3")
    set('springCredhubVersion', "4.0.1")
}

springBoot {
    buildInfo {
        properties {
            additional = [
                    'spring.boot.version': "${springBootVersion}"
            ]
        }
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework:spring-aspects'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-flyway'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.flywaydb:flyway-database-postgresql'

    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    implementation 'io.pivotal.spring.cloud:spring-cloud-services-starter-service-registry'
    implementation 'io.pivotal.spring.cloud:spring-cloud-services-starter-config-client'
    implementation "io.pivotal.cfenv:java-cfenv-boot:${javaCfenvVersion}"
    implementation "io.pivotal.cfenv:java-cfenv-boot-pivotal-sso:${javaCfenvVersion}"
    implementation "org.springframework.credhub:spring-credhub-starter:${springCredhubVersion}"
    implementation 'org.springframework.cloud:spring-cloud-bindings:2.0.4'

    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'org.testcontainers:junit-jupiter'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        mavenBom "org.testcontainers:testcontainers-bom:${testcontainersVersion}"
        mavenBom "io.pivotal.spring.cloud:spring-cloud-services-dependencies:${springCloudServicesVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
