management:
  endpoints:
    web:
      exposure:
        include: info,health

spring:
  application:
    name: acme-identity
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI:${ssoServiceUrl}/token_keys}
