logging.level:
  org.springframework.data: warn

spring:
  application:
    name: 'acme-identity'
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost/keys