
management:
  endpoints:
    web:
      exposure:
        include: info,health
spring:
  application:
    name: acme-assist
  autoconfigure:
    exclude: org.springframework.ai.autoconfigure.vectorstore.pgvector.PgVectorStoreAutoConfiguration
