spring:
  ai:
    azure:
      openai:
        chat:
          options:
            deployment-name: gpt-35-turbo-16k
        embedding:
          options:
            deployment-name: text-embedding-ada-002
management:
  endpoints:
    web:
      exposure:
        include: info,health