
management:
  endpoints:
    web:
      exposure:
        include: info,health
spring:
  ai:
    openai:
      embedding:
        options:
          model: text-embedding-ada-002
        base-url: "https://api.openai.com"
        api-key: ${EMBEDDING_OPEN_AI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
        base-url: "https://api.openai.com"
        api-key: ${EMBEDDING_OPEN_AI_API_KEY}
  application:
    name: acme-assist
  autoconfigure:
    exclude:
    - org.springframework.ai.autoconfigure.vectorstore.pgvector.PgVectorStoreAutoConfiguration
  cloud:
    config:
      enabled: false

