management:
  endpoints:
    web:
      exposure:
        include: info,health
spring:
  ai:
    model:
      chat: none
      embedding: none
      audio:
        speech: none
        transcription: none
      image: none
      moderation: none
    vectorstore:
      pgvector:
        initialize-schema: true
        remove-existing-vector-store-table: true
  application:
    name: acme-assist
  threads:
    virtual:
      enabled: true
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
