name: Catalog
on:
  workflow_dispatch:
    inputs: { }
  push:
    branches:
      - Azure
    paths:
      - 'apps/acme-catalog/**'
env:
  SPRING_CLOUD_SERVICE: ${{ secrets.TF_PROJECT_NAME }}-asc
  RESOURCE_GROUP: ${{ secrets.TF_PROJECT_NAME }}-resources
  CATALOG_SERVICE_APP: catalog-service

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/acme-catalog
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
#TODO: tests are failing
          arguments: build -x test
          build-root-directory: apps/acme-catalog
      - name: Set up Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Azure Spring Extension
        run: az extension add --name spring-cloud
      - name: Deploy Catalog
        run: |
          az spring-cloud app deploy \
            --name ${CATALOG_SERVICE_APP} \
            --resource-group "$RESOURCE_GROUP" \
            --service "$SPRING_CLOUD_SERVICE" \
            --config-file-pattern catalog/default \
            --artifact-path ./build/libs/acme-catalog-0.0.1-SNAPSHOT.jar