name: Cleanup
on:
  workflow_dispatch:
    inputs: { }

jobs:
  destory:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        id: first-plan
        continue-on-error: true
        run: |
          terraform plan -destroy -input=false \
            -var "project_name=${{ secrets.TF_PROJECT_NAME}}" \
            -var "resource_group_location=${{ secrets.AZURE_LOCATION }}"
      - name: Terraform Apply
        if: steps.first-plan.outcome == 'success'
        id: first-apply
        continue-on-error: true
        run: |
          terraform apply -destroy -auto-approve -input=false \
            -var "project_name=${{ secrets.TF_PROJECT_NAME}}" \
            -var "resource_group_location=${{ secrets.AZURE_LOCATION }}"
      - name: Terraform Plan (Second Attempt, if the first one failed)
        if: steps.first-apply.outcome != 'success'
        id: second-plan
        continue-on-error: true
        run: |
          terraform plan -destroy -input=false \
            -var "project_name=${{ secrets.TF_PROJECT_NAME}}" \
            -var "resource_group_location=${{ secrets.AZURE_LOCATION }}"
      - name: Terraform Apply (Second Attempt, if the first one failed)
        if: steps.second-plan.outcome == 'success'
        id: second-apply
        continue-on-error: true
        run: |
          terraform apply -destroy -auto-approve -input=false \
            -var "project_name=${{ secrets.TF_PROJECT_NAME}}" \
            -var "resource_group_location=${{ secrets.AZURE_LOCATION }}"
      - name: Terraform Plan (Third Attempt, if the first one and second one failed)
        if: steps.first-apply.outcome != 'success' && steps.second-apply.outcome != 'success'
        id: third-plan
        continue-on-error: true
        run: |
          terraform plan -destroy -input=false \
            -var "project_name=${{ secrets.TF_PROJECT_NAME}}" \
            -var "resource_group_location=${{ secrets.AZURE_LOCATION }}"
      - name: Terraform Apply (Third Attempt, if the first one and second one failed)
        if: steps.third-plan.outcome == 'success'
        continue-on-error: true
        run: |
          terraform apply -destroy -auto-approve -input=false \
            -var "project_name=${{ secrets.TF_PROJECT_NAME}}" \
            -var "resource_group_location=${{ secrets.AZURE_LOCATION }}"
