name: Deploy Order
on:
  workflow_dispatch:
    inputs: { }
  push:
    branches:
      - Azure
    paths:
      - 'apps/acme-order/**'
env:
  SPRING_CLOUD_SERVICE: ${{ secrets.TF_PROJECT_NAME }}-asc
  RESOURCE_GROUP: ${{ secrets.TF_PROJECT_NAME }}-resources
  CUSTOM_BUILDER: no-bindings-builder
  ORDER_SERVICE_APP: order-service
  ORDER_SERVICE_DB_CONNECTION: order_service_db

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/acme-order
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v2
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Set up Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Azure Spring Extension
        run: az extension add --name spring-cloud
      - name: Deploy Order
        run: |
          postgres_connection_str=$(az spring-cloud connection show \
            --resource-group ${RESOURCE_GROUP} \
            --service ${SPRING_CLOUD_SERVICE} \
            --deployment default \
            --connection ${ORDER_SERVICE_DB_CONNECTION} \
            --app ${ORDER_SERVICE_APP} | jq '.configurations[0].value' -r)

          gateway_url=$(az spring-cloud gateway show \
            --resource-group ${RESOURCE_GROUP} \
            --service ${SPRING_CLOUD_SERVICE} | jq -r '.properties.url')

          az spring-cloud app deploy \
            --name ${ORDER_SERVICE_APP} \
            --resource-group "$RESOURCE_GROUP" \
            --service "$SPRING_CLOUD_SERVICE" \
            --builder ${CUSTOM_BUILDER} \
            --env "AcmeServiceSettings__AuthUrl=https://${gateway_url}" "ConnectionStrings__OrderContext=$postgres_connection_str" \
            --source-path ./