name: Payment
on:
  workflow_dispatch:
    inputs: { }
  push:
    branches:
      - Azure
    paths:
      - 'apps/acme-payment/**'
env:
  SPRING_CLOUD_SERVICE: ${{ secrets.TF_PROJECT_NAME }}-asc
  RESOURCE_GROUP: ${{ secrets.TF_PROJECT_NAME }}-resources
  PAYMENT_SERVICE_APP: payment-service

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/acme-payment
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: apps/acme-payment
      - name: Set up Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Azure Spring Extension
        run: az extension add --name spring-cloud
      - name: Deploy Payment
        run: |
          az spring-cloud app deploy \
            --name ${PAYMENT_SERVICE_APP} \
            --resource-group "$RESOURCE_GROUP" \
            --service "$SPRING_CLOUD_SERVICE" \
            --config-file-pattern payment/default \
            --artifact-path ./build/libs/acme-payment-0.0.1-SNAPSHOT.jar